CREATE TABLE IF NOT EXISTS Vendors (
    VendorID INTEGER PRIMARY KEY AUTOINCREMENT,
    VendorName TEXT NOT NULL UNIQUE,
    VendorIsActive INTEGER NOT NULL DEFAULT 1,
    CreationTimestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trigger_vendors_updated_at AFTER UPDATE ON Vendors
BEGIN
    UPDATE Vendors SET UpdatedAt = CURRENT_TIMESTAMP WHERE VendorID = NEW.VendorID;
END;
