CREATE TABLE IF NOT EXISTS Entities (
    EntityID INTEGER PRIMARY KEY AUTOINCREMENT,
    EntityName TEXT NOT NULL UNIQUE,
    EntityIsActive INTEGER NOT NULL DEFAULT 1,
    CreationTimestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trigger_entities_updated_at AFTER UPDATE ON Entities
BEGIN
    UPDATE Entities SET UpdatedAt = CURRENT_TIMESTAMP WHERE EntityID = NEW.EntityID;
END;
