CREATE TABLE IF NOT EXISTS Stores (
    StoreID INTEGER PRIMARY KEY AUTOINCREMENT,
    StoreName TEXT NOT NULL UNIQUE,
    StoreIsActive INTEGER NOT NULL DEFAULT 1,
    CreationTimestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trigger_stores_updated_at AFTER UPDATE ON Stores
BEGIN
    UPDATE Stores SET UpdatedAt = CURRENT_TIMESTAMP WHERE StoreID = NEW.StoreID;
END;
