CREATE TABLE IF NOT EXISTS Categories (
    CategoryID INTEGER PRIMARY KEY AUTOINCREMENT,
    CategoryName TEXT NOT NULL UNIQUE,
    CategoryIsActive INTEGER NOT NULL DEFAULT 1,
    CreationTimestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trigger_categories_updated_at AFTER UPDATE ON Categories
BEGIN
    UPDATE Categories SET UpdatedAt = CURRENT_TIMESTAMP WHERE CategoryID = NEW.CategoryID;
END;
