CREATE TABLE IF NOT EXISTS Debtors (
    DebtorID INTEGER PRIMARY KEY AUTOINCREMENT,
    DebtorName TEXT NOT NULL UNIQUE,
    DebtorIsActive INTEGER NOT NULL DEFAULT 1,
    CreationTimestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trigger_debtors_updated_at AFTER UPDATE ON Debtors
BEGIN
    UPDATE Debtors SET UpdatedAt = CURRENT_TIMESTAMP WHERE DebtorID = NEW.DebtorID;
END;
