-- Merged into 20240523085016_income_schedules.sql
-- This file is kept for migration history but its content is now part of the main table definition.
-- Original content:
-- ALTER TABLE IncomeSchedules ADD COLUMN Type TEXT NOT NULL DEFAULT 'income';
-- ALTER TABLE IncomeSchedules ADD COLUMN StoreID INTEGER REFERENCES Stores(StoreID);
-- ALTER TABLE IncomeSchedules ADD COLUMN CategoryID INTEGER REFERENCES Categories(CategoryID);
-- ... (and the table recreation logic)
